# Generated by Django 4.1.7 on 2023-05-08 14:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reception_suggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reception',
            options={'ordering': ['id'], 'verbose_name': 'Прием', 'verbose_name_plural': 'Интернет-Приемная'},
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['id'], 'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/blog/static/blog/'), upload_to='pdfs/', verbose_name='PDF-файл'),
        ),
    ]
