# Generated by Django 4.1.7 on 2023-05-08 15:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_reception_options_alter_suggestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\IT\\Orders\\nizhnegnutov.rf\\website\\static'), upload_to='blog/pdfs/', verbose_name='PDF-файл'),
        ),
    ]
