# Generated by Django 4.1.7 on 2023-05-08 17:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\IT\\Orders\\nizhnegnutov.rf\\website\\blog'), upload_to='static/blog/pdfs/', verbose_name='PDF-файл'),
        ),
    ]
